// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpnbgzibqehvhhsrbccd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwbmJnemlicWVodmhoc3JiY2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDI3NzcsImV4cCI6MjA2NzI3ODc3N30.usn_dhutaU-2E-FlOlA7OieWuPsWzpIilorUiYA9B6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});